### PR TITLE
Login test

### LINKED ISSUE #42: [Testing] Create LoginController Integration test
Use ~WebMvcTest~ SpringBootTest and MockMvc to write integration tests for the login method.

Write test cases for each possibility (is it necessary if i am already unit testing my interactor?) :

- [x] Successful login
- [x]  Wrong Password
- [x] Invalid username

**Helpful links/resources used:**
- https://www.youtube.com/watch?v=pNiRNRgi5Ws (ended up not following this method which used WebMvcTest)
- https://stackoverflow.com/questions/18336277/how-to-check-string-in-response-body-with-mockmvc
- https://stackoverflow.com/questions/51873620/is-there-a-method-built-in-spring-mockmvc-to-get-json-content-as-object

https://github.com/ClaimsCompass/ClaimsCompass/pull/43

### PR DESCRIPTION
**Pull request by Krisha-11**
## Motivation

This pull request is for adding Login Use case Interactor and Controller tests to the main. 
It also adds uint tests for Claims entity

## Changes

- added Claims entity unit tests
- refactored Login use case code to follow CA engine better (edited controller to handle http requests and made controller return a boolean; added InputData class and InputDataBoundary interface. 
- added integration testing for Login Controller
- added unit testing for Login Interactor
- modified pom.xml to add junit5 and springboot testing dependencies
- unmarked src as sources root to resolve 'package org.junit.jupiter.api does not exist' error while testing (this modified the iml file)

**Type of change** (select all that apply):

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Refactoring (internal change to codebase, without changing functionality)
- [X] Test update (change that modifies or updates tests only)
- [ ] Documentation update (change that modifies or updates documentation only)
- [ ] Other (please specify):

## Testing

Ran the Login Use case tests in IntelliJ. All tests passed. 

## Remarks
Closes #42

### CODE REVIEW

File: src/main/java/com/securian/creditcompass/login/LoginInteractor.java
Comment (derekdhuynh) [inline src/main/java/com/securian/creditcompass/login/LoginInteractor.java:1]: Good changes, but I think Ron was looking to work on this. Could you coordinate with him so he's working on something not already implemented?

File: src/main/java/com/securian/creditcompass/login/LoginInteractor.java [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+    public boolean authenticate(LoginInputData loginInputData) throws AuthenticationException{
+        // Create a ClaimsExaminer object from the username's equivalent in the database'
+        Optional<ClaimsExaminer> optionalExaminer = loginDataAccessInterface.findByUsername(loginInputData.getUsername());
+        if (optionalExaminer.isPresent()){
+            ClaimsExaminer examiner = optionalExaminer.get();
+            // get the password from the ClaimsExaminer object
+            String dbPassword = examiner.getPassword();
+
+            // compare database value to the password in the loginInputData
+            if(dbPassword.equals(loginInputData.getPassword())){
```
Comment (derekdhuynh) [inline src/main/java/com/securian/creditcompass/login/LoginInteractor.java:26]: Styling, there should be white space between the condition and the "if" keyword. Also I believe there should be whitespace before the first curly brace. I have made comments on other lines where I noticed it as well.

File: src/main/java/com/securian/creditcompass/login/LoginController.java [hunk 2]
```diff
@@ -1,22 +1,36 @@
...
     @PostMapping("/login")
-    public ResponseEntity<Object> login(@RequestBody LoginDataTransferObject loginDataTransferObject) {
-        return loginService.authenticate(loginDataTransferObject.getUsername(), loginDataTransferObject.getPassword());
+    public ResponseEntity<String> login(@RequestBody Map<String, String> userInput) {
+        String username = userInput.get("username");
+        String password = userInput.get("password");
+        LoginInputData loginInputData = new LoginInputData(username, password);
+        try{
+            boolean authenticated = loginService.authenticate(loginInputData);
+            if(authenticated){
```
Comment (derekdhuynh) [inline src/main/java/com/securian/creditcompass/login/LoginController.java:25]: Style.

File: src/main/java/com/securian/creditcompass/login/LoginController.java [hunk 3]
```diff
@@ -1,22 +1,36 @@
...
+                return ResponseEntity.ok("Logging you in...");
+            } else {
+                return ResponseEntity.status(401).body("Login unsuccessful.");
+            }
+        } catch (AuthenticationException e){
```
Comment (derekdhuynh) [inline src/main/java/com/securian/creditcompass/login/LoginController.java:30]: Style.

File: src/main/java/com/securian/creditcompass/login/LoginInteractor.java [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+
+@Service
+public class LoginInteractor implements LoginInputBoundary{
+    private final LoginDataAccessInterface loginDataAccessInterface;
+    public LoginInteractor(LoginDataAccessInterface loginDataAccessInterface){
+        this.loginDataAccessInterface = loginDataAccessInterface;
+    }
+
+    @Override
+    public boolean authenticate(LoginInputData loginInputData) throws AuthenticationException{
```
Comment (derekdhuynh) [inline src/main/java/com/securian/creditcompass/login/LoginInteractor.java:17]: Probably good to return Boolean instead of the primitive boolean for OOP reasons, I believe the TA's or Maryam said something about this.

**Review by derekdhuynh — COMMENTED** [review]
No major issues I encountered, I left some comments regarding code style and some conventions, but overall looks ready. Overall the tests seem reasonable.
